// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import context "context"
import domain "infodesk/domain"
import mock "github.com/stretchr/testify/mock"

// ArticleRepository is an autogenerated mock type for the ArticleRepository type
type BankRepository struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, cursor, num
func (_m *BankRepository) FetchBanks(ctx context.Context) ([]domain.BeneficiaryBank, error) {
	ret := _m.Called(ctx)

	var r0 []domain.BeneficiaryBank
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BeneficiaryBank); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BeneficiaryBank)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *BankRepository) FetchBankBranches(ctx context.Context, typeCode *int, province string, city string) ([]domain.BankNode, error) {
	ret := _m.Called(ctx)

	var r0 []domain.BankNode
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BankNode); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BankNode)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
